# Generated by Django 4.2.6 on 2023-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="report_by",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
