# Generated by Django 4.2.6 on 2023-10-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_transaction_report_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="report_by",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="visa",
            field=models.CharField(
                choices=[
                    ("Tourist", "Tourist"),
                    ("Visiting Relatives", "Visiting Relatives"),
                ],
                max_length=100,
            ),
        ),
    ]
