# Generated by Django 4.2.6 on 2023-10-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_alter_transaction_report_by_alter_transaction_visa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="visa",
            field=models.CharField(
                choices=[
                    ("Tourist", "Tourist"),
                    ("Visiting Relatives", "Visiting Relatives"),
                ],
                default="Tourist",
                max_length=100,
            ),
        ),
    ]
