# Generated by Django 4.2.6 on 2023-10-27 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_alter_transaction_visa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="pax",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
