# Generated by Django 4.2.6 on 2023-10-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0006_alter_transaction_pax_alter_transaction_report_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="report_by",
            field=models.CharField(
                choices=[("mark", "mark")], default="select", max_length=100
            ),
        ),
    ]
