# Generated by Django 4.2.6 on 2023-10-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_alter_transaction_report_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="visa",
            field=models.CharField(
                choices=[
                    ("TOURISM", "TOURISM"),
                    ("PACKAGE TOUR", "PACKAGE TOUR"),
                    (
                        "BUSINESS, CONFERENCE OR CULTURAL EXCHANGE, etc.",
                        "BUSINESS, CONFERENCE OR CULTURAL EXCHANGE, etc.",
                    ),
                    ("VISITING RELATIVES", "VISITING RELATIVES"),
                    (
                        "VISITING FRIENDS OR DISTANT RELATIVES",
                        "VISITING FRIENDS OR DISTANT RELATIVES",
                    ),
                    (
                        "VISITING US MILITARY PERSONNEL",
                        "VISITING US MILITARY PERSONNEL",
                    ),
                    (
                        "SPOUSE OR CHILDD OF JAPANESE NATIONAL RESIDING IN THE PHILIPPINES",
                        "SPOUSE OR CHILD OF JAPANESE NATIONAL RESIDING IN THE PHILIPPINES",
                    ),
                    ("TRANSIT", "TRANSIT"),
                    ("DIPLOMAT/OFFICIAL", "DIPLOMAT/OFFICIAL"),
                    (
                        "HOUSEKEEPER OF DIPLOMAT/OFFICIAL",
                        "HOUSEKEEPER OF DIPLOMAT/OFFICIAL",
                    ),
                    (
                        "NIKKEI-JIN (JAPANESE DESCENDANT)",
                        "NIKKEI-JIN (JAPANESE DESCENDANT)",
                    ),
                    (
                        "FILIPINO PARENTS TRAVELLING TO JAPAN WITH JAPANESE-FILIPINO CHILDREN",
                        "FILIPINO PARENTS TRAVELLING TO JAPAN WITH JAPANESE-FILIPINO CHILDREN",
                    ),
                    ("COE", "COE"),
                ],
                default="Tourist",
                max_length=100,
            ),
        ),
    ]
