# Generated by Django 4.2.6 on 2023-10-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_alter_transaction_visa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="report_by",
            field=models.CharField(
                choices=[
                    ("RV", "RV"),
                    ("PAUL", "PAUL"),
                    ("JOEVIL", "JOEVIL"),
                    ("AIMEE", "AIMEE"),
                    ("ARJANE", "ARJANE"),
                ],
                default="select",
                max_length=100,
            ),
        ),
    ]
